
import { StyleSheet } from "react-native";

export const createGroupFormStyle = (theme: any, s: any) =>
    StyleSheet.create({
        card: {
            borderRadius: 30,
            padding: 20,
            margin: 1,
            shadowColor: theme.shadowColor,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.25,
            shadowRadius: 8,
            elevation: 6,
        },
        subtitle: {
            fontSize: 18,
            fontWeight: "600",
            marginBottom: 16,
            color: theme.text,
            fontFamily: theme.fontFamily,
        },
        inputContainer: {
            marginBottom: 12,
        },
        input: {
            backgroundColor: theme.inputBg,
            borderRadius: 30,
            paddingHorizontal: s(20),
            paddingVertical: s(16),
            flexDirection: "row",
            alignItems: "center",
            borderWidth: 2,
            borderColor: theme.inputBorder,
            shadowColor: theme.shadowColor,
            shadowOpacity: 0.3,
            shadowRadius: s(16),
            elevation: 16,
            marginBottom: s(20),
        },
        textAreaContainer: {
            height: 90,
        },
        textArea: {
            textAlignVertical: "top",
            height: "100%",
            paddingTop: 20,
        },
        label: {
            fontSize: 14,
            fontWeight: "500",
            color: theme.textSecondary,
            marginBottom: 8,
            marginTop: 16,
            fontFamily: theme.fontFamily,
        },
        dpPicker: {
            width: 80,
            height: 80,
            borderRadius: 40,
            overflow: "hidden",
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: theme.bgSecondary,
            alignSelf: "center",
            marginBottom: 20,
        },
        dpImage: {
            width: "100%",
            height: "100%",
            borderRadius: 40,
        },
        dpFallback: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: theme.border,
            width: "100%",
            height: "100%",
        },
        dpFallbackText: {
            fontSize: 32,
            fontWeight: "600",
            color: theme.text,
            fontFamily: theme.fontFamily,
        },
        button: {
            backgroundColor: theme.button,
            borderRadius: 30,
            paddingHorizontal: s(20),
            paddingVertical: s(16),
            alignItems: "center",
            borderWidth: 2,
            borderColor: theme.inputBorder,
            shadowColor: theme.shadowColor,
            shadowOpacity: 0.3,
            shadowRadius: s(16),
            elevation: 16,
            marginBottom: s(20),
        },
        buttonText: {
            color: theme.sentText,
            fontWeight: "600",
            fontSize: 16,
            fontFamily: theme.fontFamily,
        },
    });
